import { useEffect, useState } from "react";
import { loadAssessment, scoreAssessment } from "@/services/assessmentService";
import { Button } from "@/components/common/Button";
import { AlertCircle, CheckCircle2, Loader2, Sparkles, BookOpenCheck, X } from "lucide-react";
import { cn } from "@/utils/cn";

// A question counts as "code-heavy" (extra 10s) when it shows code.
const CODE_PATTERN = /```|\(\)|=>|===|;|SELECT|print\(|def |function |const |let |\{|\}|\b\d+\s*[\+\-\*\/]\s*\d+/i;
const BASE_SECONDS = 60;
const CODE_BONUS_SECONDS = 10;

function isCodeQuestion(q) {
  const text = [q?.q, ...(q?.options || [])].join(" ");
  return CODE_PATTERN.test(text);
}

export function timeForQuestions(questions) {
  const codeCount = (questions || []).filter(isCodeQuestion).length;
  return BASE_SECONDS + codeCount * CODE_BONUS_SECONDS;
}

function formatClock(totalSeconds) {
  const s = Math.max(0, totalSeconds);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
}

export default function AssessmentModal({ skillName, onComplete, onClose }) {
  const [loading, setLoading] = useState(true);
  const [questions, setQuestions] = useState([]);
  const [source, setSource] = useState(null);
  const [error, setError] = useState("");
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState({});
  const [result, setResult] = useState(null);
  const [secondsLeft, setSecondsLeft] = useState(null);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true);
      setError("");
      try {
        const { questions: qs, source: src } = await loadAssessment(skillName, 5);
        if (!cancelled) {
          setQuestions(qs);
          setSource(src);
        }
      } catch (err) {
        if (!cancelled) setError(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, [skillName]);

  const current = questions[index];
  const done = result !== null;

  const handleFinish = () => {
    const score = scoreAssessment(questions, answers);
    setResult({ score, timedOut: false });
  };

  // Countdown: 60s for 5 questions + 10s per code question. Auto-submits at zero.
  useEffect(() => {
    if (loading || error || questions.length === 0) return;
    setSecondsLeft((prev) => (prev === null ? timeForQuestions(questions) : prev));
  }, [loading, error, questions]);

  useEffect(() => {
    if (secondsLeft === null || done || loading || error) return;
    if (secondsLeft <= 0) {
      const score = scoreAssessment(questions, answers);
      setResult({ score, timedOut: true });
      return;
    }
    const t = setTimeout(() => setSecondsLeft((s) => s - 1), 1000);
    return () => clearTimeout(t);
  }, [secondsLeft, done, loading, error, questions, answers]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4" onClick={onClose}>
      <div
        className="w-full max-w-lg bg-white dark:bg-slate-900 rounded-2xl shadow-xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800">
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white">Skill assessment: {skillName}</h3>
            {!loading && !error && (
              <p className="text-xs text-slate-500 mt-0.5 flex items-center gap-1">
                {source === "gemini" ? (
                  <><Sparkles className="h-3 w-3 text-primary-500" /> Questions generated by AI</>
                ) : (
                  <><BookOpenCheck className="h-3 w-3" /> Standard question bank</>
                )}
                {" "}· Question {Math.min(index + 1, questions.length)} of {questions.length}
              </p>
            )}
          </div>
          {!loading && !error && !done && secondsLeft !== null && (
            <span className={cn(
              "shrink-0 font-mono text-sm font-bold px-2.5 py-1 rounded-lg",
              secondsLeft <= 15
                ? "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400"
                : "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300"
            )}>
              {formatClock(secondsLeft)}
            </span>
          )}
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-6">
          {loading ? (
            <div className="py-10 text-center text-slate-500">
              <Loader2 className="h-8 w-8 mx-auto mb-3 animate-spin text-primary-500" />
              <p className="text-sm">Preparing your assessment...</p>
            </div>
          ) : error ? (
            <div className="p-4 rounded-lg bg-amber-50 text-amber-700 border border-amber-100 dark:bg-amber-900/20 dark:border-amber-900/50 dark:text-amber-400 flex items-start gap-3">
              <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium">{error}</p>
                <Button size="sm" variant="outline" className="mt-3" onClick={onClose}>
                  Go Back
                </Button>
              </div>
            </div>
          ) : done ? (
            <div className="text-center py-4">
              {result.timedOut && (
                <p className="text-xs font-semibold text-amber-600 dark:text-amber-400 mb-2">
                  Time expired — submitted automatically.
                </p>
              )}
              <CheckCircle2 className={cn(
                "h-14 w-14 mx-auto mb-3",
                result.score >= 70 ? "text-emerald-500" : "text-amber-500"
              )} />
              <p className="text-4xl font-black text-slate-900 dark:text-white">{result.score}%</p>
              <p className="text-sm text-slate-500 mt-2 max-w-sm mx-auto">
                {result.score >= 70
                  ? `Strong proof — "${skillName}" will be saved at ${result.score}% and marked Partially Verified.`
                  : `"${skillName}" will be saved at ${result.score}% as Claimed. Retake later to verify it.`}
              </p>
              <div className="flex gap-3 justify-center mt-6">
                <Button variant="outline" onClick={onClose}>Discard</Button>
                <Button onClick={() => onComplete(result.score)}>Save Skill</Button>
              </div>
            </div>
          ) : (
            <>
              <p className="font-medium text-slate-900 dark:text-white mb-4">{current.q}</p>
              <div className="space-y-2">
                {current.options.map((opt, i) => (
                  <button
                    key={i}
                    onClick={() => setAnswers((a) => ({ ...a, [index]: i }))}
                    className={cn(
                      "w-full text-left px-4 py-2.5 rounded-lg border text-sm transition-colors",
                      answers[index] === i
                        ? "border-primary-500 bg-primary-50 text-primary-700 dark:bg-primary-900/30 dark:text-primary-300"
                        : "border-slate-200 text-slate-700 hover:border-slate-300 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"
                    )}
                  >
                    {opt}
                  </button>
                ))}
              </div>
              <div className="flex items-center justify-between mt-6">
                <Button
                  variant="ghost"
                  size="sm"
                  disabled={index === 0}
                  onClick={() => setIndex((v) => v - 1)}
                >
                  Back
                </Button>
                {index + 1 < questions.length ? (
                  <Button size="sm" disabled={answers[index] === undefined} onClick={() => setIndex((v) => v + 1)}>
                    Next
                  </Button>
                ) : (
                  <Button
                    size="sm"
                    disabled={Object.keys(answers).length < questions.length}
                    onClick={handleFinish}
                  >
                    See Results
                  </Button>
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
